version: '3.8'

services:

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  account-service:
    build:
      context: .
      dockerfile: account-service/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      - zipkin

  event-gateway:
    build:
      context: .
      dockerfile: event-gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ACCOUNT_SERVICE_BASE_URL=http://account-service:8081
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      - account-service
      - zipkin
